### Get All Courses
GET http://localhost:3000/courses

### Get corses By Id
GET http://localhost:3000/courses/240c70a8-d32f-49cb-9308-9d7fd6c2b439

### Get By query
GET http://localhost:3000/courses/search?s=b39a959e-3ad8-4ada-8607-5a6401456528

### Resgister course
POST http://localhost:3000/courses
Content-Type: application/json

{
    "name": "React",
    "description": "Curso de React",
    "tags": ["React", "javaScript", "Front-End"]
}

### Edit Course
PATCH   http://localhost:3000/courses/d5017a3b-0910-4d2d-ac67-97ed3acb0cf8
Content-Type: application/json

{
    "description": "teste2",
    "tags": ["Teste"]
}

### Delete Course
DELETE  http://localhost:3000/courses/4b58ff72-9ad9-40ba-97f4-3c3dffadfb4e
