### SingUp
POST http://localhost:3000/user
Content-Type: application/json 

{
    "name": "teste",
    "email": "teste@email.com",
    "password": "123"
}

### Login
# @name login
POST http://localhost:3000/user/login
Content-Type: application/json 

{
    "email": "teste@email.com",
    "password": "123"
}

###
@token = {{login.response.body.token}}
###

### Get All Users
GET http://localhost:3000/user
Authorization: {{token}}

### Get User By Id
GET http://localhost:3000/user/c07e7872-e97d-4b22-9083-c7f18c284530

### Delete User
DELETE http://localhost:3000/user/119fe2a3-ca2c-40fb-9f74-fc25fdcaca5e

### Get All Courses
GET http://localhost:3000/courses
Authorization: {{token}}

### Get corses By Id
GET http://localhost:3000/courses/6df75d6d-a2d1-4220-a3bc-8630d4fa190e
Authorization: {{token}}

### Get By query
GET http://localhost:3000/courses/search?s=6df75d6d-a2d1-4220-a3bc-8630d4fa190e
Authorization: {{token}}

### Resgister course
POST http://localhost:3000/courses
Authorization: {{token}}
Content-Type: application/json

{
    "name": "NestJS",
    "description": "Curso de Nest, Node e Type",
    "tags": []
}

### Edit Course
PATCH   http://localhost:3000/courses/74f10589-cb31-4e17-99df-3a39bbdd2e13
Authorization: {{token}}
Content-Type: application/json

{
    "description": "Curso de NestJS, NodeJS e TypeORM",
    "tags": ["NestJS","NodeJS","TypeORM"]
}

### Delete Course
DELETE  http://localhost:3000/courses/64ec2b2a-e342-420b-a353-1addb0a32e5d
Authorization: {{token}}
