version: '3'

services:
  app: 
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: nestJS-app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   tty: true
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - 8000:80
  #   depends_on:
  #     - db

  db:
    image: postgres:alpine3.16
    container_name: postgres-db
    restart: always
    tty: true
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: postgres
