version: '3'

services:
  # app: 
  #   build: .
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/home/node/app
  #   depends_on:
  #     - db
  
  db:
    image: postgres:alpine3.16
    restart: always
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: postgres
